# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - init: |
      cd angular-blog
      npm install
    command: npm start

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports


# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
